index:
  path: /
  defaults: { _controller: AppBundle:Default:index, _locale: es }

login:
  path: /login
  defaults: { _controller: AppBundle:Security:login }

logout:
  path: /logout

login_check:
  path: /login_check
  defaults: { _controller: AppBundle:Default:index }

user:
  path: /user
  defaults: { _controller: AppBundle:User:default }

newCliente:
  path: /cliente/new
  defaults: { _controller: AppBundle:Cliente:new }

editCliente:
  path: /cliente/edit/{id}
  defaults: { _controller: AppBundle:Cliente:edit }
  requirements:
    id: \d+

deleteCliente:
  path: /cliente/delete/{id}
  defaults: { _controller: AppBundle:Cliente:delete }
  requirements:
    id: \d+
showCliente:
  path: /cliente/show/{id}
  defaults: { _controller: AppBundle:Cliente:show }
  requirements:
    id: \d+

newAdministrador:
  path: /admin/new
  defaults: { _controller: AppBundle:Administrador:new }

editAdministrador:
  path: /admin/edit/{id}
  defaults: { _controller: AppBundle:Administrador:edit }
  requirements:
    id: \d+

deleteAdministrador:
  path: /admin/delete/{id}
  defaults: { _controller: AppBundle:Administrador:delete }
  requirements:
    id: \d+

showAdministrador:
  path: /admin/show/{id}
  defaults: { _controller: AppBundle:Administrador:show }
  requirements:
    id: \d+

newHelpDesk:
  path: /helpdesk/new
  defaults: { _controller: AppBundle:HelpDesk:new }

editHelpDesk:
  path: /helpdesk/edit/{id}
  defaults: { _controller: AppBundle:HelpDesk:edit }
  requirements:
    id: \d+

deleteHelpDesk:
  path: /helpdesk/delete/{id}
  defaults: { _controller: AppBundle:HelpDesk:delete }
  requirements:
    id: \d+

showHelpDesk:
  path: /helpdesk/show/{id}
  defaults: { _controller: AppBundle:HelpDesk:show }
  requirements:
    id: \d+

newTecnico:
  path: /tecnico/new
  defaults: { _controller: AppBundle:Tecnico:new }

editTecnico:
  path: /tecnico/edit/{id}
  defaults: { _controller: AppBundle:Tecnico:edit }
  requirements:
    id: \d+

deleteTecnico:
  path: /tecnico/delete/{id}
  defaults: { _controller: AppBundle:Tecnico:delete }
  requirements:
    id: \d+

showTecnico:
  path: /tecnico/show/{id}
  defaults: { _controller: AppBundle:Tecnico:show }
  requirements:
    id: \d+

incidencia:
  path: /incidencia
  defaults: { _controller: AppBundle:Incidencia:default }

newIncidencia:
  path: /incidencia/new
  defaults: { _controller: AppBundle:Incidencia:new }

editIncidencia:
  path: /incidencia/edit/{id}
  defaults: { _controller: AppBundle:Incidencia:edit }
  requirements:
    id: \d+

deleteIncidencia:
  path: /incidencia/delete/{id}
  defaults: { _controller: AppBundle:Incidencia:delete }
  requirements:
    id: \d+

listIncidencia:
  path: /incidencia/list
  defaults: { _controller: AppBundle:Incidencia:list }

showIncidencia:
  path: /incidencia/show/{id}
  defaults: { _controller: AppBundle:Incidencia:show }
  requirements:
    id: \d+

#newEstado:
#  path: /estado/new
#  defaults: { _controller: AppBundle:Estado:new }

#editEstado:
#  path: /estado/edit/{id}
#  defaults: { _controller: AppBundle:Estado:edit }
#  requirements:
#    id: \d+

#deleteEstado:
#  path: /estado/delete/{id}
#  defaults: { _controller: AppBundle:Estado:delete }
#  requirements:
#    id: \d+